# Ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
    nodejs: "22"
  jobs:
    pre_create_environment:
      - npm install -g aws-cdk@2.1010.0

sphinx:
  configuration: docs/source/conf.py

python:
  install:
  - method: pip
    path: .
  - requirements: requirements.txt
  - requirements: requirements-doc.txt
